Repository CSID-DGU/Re-MLAC, pull requests merged in 2024-03, with the labels that each got.

#12 ✨ Feature - Packet Filter Server
  build.gradle
  src/main/java/org/dongguk/mlac/controller/FirewallLogController.java
  src/main/java/org/dongguk/mlac/domain/Attack.java
  src/main/java/org/dongguk/mlac/domain/FirewallLog.java
  src/main/java/org/dongguk/mlac/dto/common/ArgumentNotValidExceptionDto.java
  src/main/java/org/dongguk/mlac/dto/common/ExceptionDto.java
  src/main/java/org/dongguk/mlac/dto/common/ResponseDto.java
  src/main/java/org/dongguk/mlac/dto/request/FilterRequestDto.java
  src/main/java/org/dongguk/mlac/dto/response/FilterResponseDto.java
  src/main/java/org/dongguk/mlac/dto/type/EAttackType.java
  src/main/java/org/dongguk/mlac/dto/type/ErrorCode.java
  src/main/java/org/dongguk/mlac/exception/CommonException.java
  src/main/java/org/dongguk/mlac/repository/FirewallLogRepository.java
  src/main/java/org/dongguk/mlac/service/FirewallLogService.java
  src/main/resources/application.yml
Labels: feature, 승준

#9 ✨ Feature - AI Analysis Server Complete
  analysis/.gitignore
  analysis/README.md
  analysis/manage.py
  analysis/mlac/__init__.py
  analysis/mlac/asgi.py
  analysis/mlac/settings.py
  analysis/mlac/urls.py
  analysis/mlac/wsgi.py
  analysis/packet/__init__.py
  analysis/packet/admin.py
  analysis/packet/apps.py
  analysis/packet/dto/packet_dto.py
  analysis/packet/migrations/__init__.py
  analysis/packet/models.py
  analysis/packet/tests.py
  analysis/packet/urls.py
  analysis/packet/views.py
  analysis/requirements.txt
Labels: feature, 창섭, 형준

#11 ✨ Feature - 공격 패킷 로그 저장 api 생성
  .gitignore
  build.gradle
  src/main/java/org/dongguk/mlac/controller/AttackController.java
  src/main/java/org/dongguk/mlac/domain/Attack.java
  src/main/java/org/dongguk/mlac/dto/AnalysisResultDto.java
  src/main/java/org/dongguk/mlac/dto/common/ExceptionDto.java
  src/main/java/org/dongguk/mlac/dto/common/ResponseDto.java
  src/main/java/org/dongguk/mlac/dto/type/EAttackType.java
  src/main/java/org/dongguk/mlac/exception/CommonException.java
  src/main/java/org/dongguk/mlac/exception/ErrorCode.java
  src/main/java/org/dongguk/mlac/exception/GlobalExceptionHandler.java
  src/main/java/org/dongguk/mlac/repository/AttackRepository.java
  src/main/java/org/dongguk/mlac/service/AttackService.java
  src/main/resources/application.yml
Labels: feature, 정우

#19 ✨ Feature: RestClientUtil 추가
  .gitignore
  README.md
  filter/.gitignore
  filter/Dockerfile
  filter/build.gradle
  filter/gradlew
  filter/src/main/java/org/dongguk/mlac/controller/FirewallLogController.java
  filter/src/main/java/org/dongguk/mlac/dto/request/AiRequestDto.java
  filter/src/main/java/org/dongguk/mlac/dto/request/FilterRequestDto.java
  filter/src/main/java/org/dongguk/mlac/dto/response/AiResponseDto.java
  filter/src/main/java/org/dongguk/mlac/dto/response/FilterResponseDto.java
  filter/src/main/java/org/dongguk/mlac/dto/type/ErrorCode.java
  filter/src/main/java/org/dongguk/mlac/service/FirewallLogService.java
  filter/src/main/java/org/dongguk/mlac/util/RestClientUtil.java
  filter/src/main/resources/application.yml
Labels: feature, 승준

#20 ✨ Feature: attack-log API 변경
  fw/.gitignore
  fw/Dockerfile
  fw/src/main/java/org/dongguk/mlac/controller/AttackController.java
  fw/src/main/java/org/dongguk/mlac/dto/request/AnalysisResultDto.java
  fw/src/main/java/org/dongguk/mlac/service/AttackService.java
  fw/src/main/resources/application.yml
Labels: feature, 승준

#23 ✨ Feature: Packet Input Server 작성
  input/.gitignore
  input/app/core/__init__.py
  input/app/core/config.py
  input/app/handlers/__init__.py
  input/app/handlers/handler.py
  input/app/routers/__init__.py
  input/app/routers/router.py
  input/app/schemas/__init__.py
  input/app/schemas/schema.py
  input/app/utils/__init__.py
  input/app/utils/category_label.py
  input/app/utils/custom_logger.py
  input/main.py
  input/requirements.txt
Labels: feature, 창섭

#24 ✨ Feature: Filter에서 공격 result 저장
  filter/.gitignore
  filter/Dockerfile
  filter/build.gradle
  filter/src/main/java/org/dongguk/mlac/MlacApplication.java
  filter/src/main/java/org/dongguk/mlac/controller/FilterLogController.java
  filter/src/main/java/org/dongguk/mlac/controller/FirewallLogController.java
  filter/src/main/java/org/dongguk/mlac/domain/AiServerLog.java
  filter/src/main/java/org/dongguk/mlac/domain/WebServerLog.java
  filter/src/main/java/org/dongguk/mlac/dto/request/FilterRequestDto.java
  filter/src/main/java/org/dongguk/mlac/dto/response/AiResponseDto.java
  filter/src/main/java/org/dongguk/mlac/dto/type/EAttackType.java
  filter/src/main/java/org/dongguk/mlac/dto/type/EBodyRegex.java
  filter/src/main/java/org/dongguk/mlac/dto/type/ErrorCode.java
  filter/src/main/java/org/dongguk/mlac/repository/AiServerLogRepository.java
  filter/src/main/java/org/dongguk/mlac/repository/WebServerLogRepository.java
  filter/src/main/java/org/dongguk/mlac/service/AiServerLogService.java
  filter/src/main/java/org/dongguk/mlac/service/FirewallLogService.java
  filter/src/main/java/org/dongguk/mlac/service/WebServerLogService.java
Labels: feature, 나연

#25 ✨ Feature: Preventing web server attacks
  ws/.gitignore
  ws/Dockerfile
  ws/HELP.md
  ws/build.gradle
  ws/gradle/wrapper/gradle-wrapper.jar
  ws/gradle/wrapper/gradle-wrapper.properties
  ws/gradlew
  ws/gradlew.bat
  ws/settings.gradle
  ws/src/main/java/org/dongguk/mlac/MlacApplication.java
  ws/src/main/java/org/dongguk/mlac/advice/ResponseAdvice.java
  ws/src/main/java/org/dongguk/mlac/controller/WebServerLogController.java
  ws/src/main/java/org/dongguk/mlac/domain/AttackRegex.java
  ws/src/main/java/org/dongguk/mlac/domain/WebServerLog.java
  ws/src/main/java/org/dongguk/mlac/dto/common/ExceptionDto.java
  ws/src/main/java/org/dongguk/mlac/dto/common/ResponseDto.java
  ws/src/main/java/org/dongguk/mlac/dto/request/AnalysisResultDto.java
  ws/src/main/java/org/dongguk/mlac/dto/type/EAttackType.java
  ws/src/main/java/org/dongguk/mlac/exception/CommonException.java
  ws/src/main/java/org/dongguk/mlac/exception/ErrorCode.java
  ws/src/main/java/org/dongguk/mlac/exception/GlobalExceptionHandler.java
  ws/src/main/java/org/dongguk/mlac/repository/AttackRegexRepository.java
  ws/src/main/java/org/dongguk/mlac/repository/WebServerLogRepository.java
  ws/src/main/java/org/dongguk/mlac/service/WebServerLogService.java
  ws/src/main/resources/data.sql
  ws/src/test/java/org/dongguk/mlac/MlacApplicationTests.java
Labels: feature, 창섭

#37 🎨 Refactor: Server integration
  README.md
  analysis/README.md
  build.sh
  docker-compose.yml
  filter/src/main/java/org/dongguk/mlac/domain/Result.java
  fw/README.md
  fw/src/main/java/org/dongguk/mlac/service/AttackService.java
  input/Dockerfile
  ws/src/main/java/org/dongguk/mlac/dto/request/AnalysisResultDto.java
  ws/src/main/java/org/dongguk/mlac/service/WebServerLogService.java
Labels: 창섭, refactor

#41 ✨ Feat: Filter logic for was
  filter/src/main/java/org/dongguk/mlac/domain/User.java
  filter/src/main/java/org/dongguk/mlac/domain/WebApplicationLog.java
  filter/src/main/java/org/dongguk/mlac/dto/request/WasRequestDto.java
  filter/src/main/java/org/dongguk/mlac/dto/type/ErrorCode.java
  filter/src/main/java/org/dongguk/mlac/interceptor/post/ResponseInterceptor.java
  filter/src/main/java/org/dongguk/mlac/repository/UserRepository.java
  filter/src/main/java/org/dongguk/mlac/repository/WebApplicationLogRepository.java
  filter/src/main/java/org/dongguk/mlac/service/FilterService.java
  was/src/main/java/org/dogguk/mlac/controller/WebApplicationLogController.java
Labels: feature, 승준

#43 ✨ Feat : 사용자 1000명 생성, 사용자 block status 업데이트 로직 작성
  was/src/main/java/org/dogguk/mlac/controller/WebApplicationLogController.java
  was/src/main/java/org/dogguk/mlac/domain/User.java
  was/src/main/java/org/dogguk/mlac/repository/UserRepository.java
  was/src/main/java/org/dogguk/mlac/service/UserService.java
Labels: feature, 정우

#45 ✨ Feature: Input server develop
  attack.sh
  build.sh
  input/app/handlers/handler.py
  input/app/utils/category_label.py
  input/app/utils/json_util.py
  input/app/utils/user_id_generator.py
Labels: feature, 창섭

#50 🎨 Refactor - Automatic Input Server
  input/app/configs/__init__.py
  input/app/configs/data.py
  input/app/configs/database.py
  input/app/core/config.py
  input/app/handlers/handler.py
  input/app/handlers/packet_handler.py
  input/app/handlers/predict_handler.py
  input/app/handlers/test_handler.py
  input/app/models/__init__.py
  input/app/models/dummy_script_model.py
  input/app/models/dummy_user_model.py
  input/app/repositories/__init__.py
  input/app/repositories/dummy_script_repository.py
  input/app/repositories/dummy_user_repository.py
  input/app/routers/router.py
  input/app/schemas/body_schema.py
  input/app/schemas/packet_info_schema.py
  input/app/schemas/schema.py
  input/app/schemas/test_schema.py
  input/app/types/__init__.py
  input/app/types/e_attack.py
  input/app/utils/category_label.py
  input/app/utils/custom_logger.py
  input/app/utils/json_util.py
  input/app/utils/label_util.py
  input/app/utils/pandas_util.py
  input/app/utils/user_id_generator.py
  input/main.py
  input/requirements.txt
  input/test/analysis.json
  input/test/backdoor.json
  input/test/benign.json
  input/test/bot.json
  input/test/ddos.json
  input/test/dos.json
  input/test/dos_goldeneye.json
  input/test/dos_hulk.json
  input/test/dos_slowhttptest.json
  input/test/dos_slowloris.json
  input/test/exploits.json
  input/test/ftp_patator.json
  input/test/fuzzers.json
  input/test/generic.json
  input/test/heartbleed.json
  input/test/infiltration.json
  input/test/portscan.json
  input/test/reconnaissance.json
  input/test/shell_code.json
  input/test/ssh_patator.json
  input/test/web_attack_brute_force.json
  input/test/web_attack_sql_injection.json
  input/test/web_attack_xss.json
  input/test/worms.json
Labels: 창섭, refactor
